version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
  build-ios:
    macos:
      xcode: "8.3.3"
  build-android:
    docker:
      - image: circleci/android:api-27-node8-alpha
  build-web:
    docker:
      - image: circleci/node:8
workflows:
  version: 2
  build-react-native:
    jobs:
      - build:
      - build-ios:
          requires:            
            - build
      - build-android:
          requires:
            - build
      - build-web:
          requires:
            - build