# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FastlanceDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  
  # Pods for FastlanceDemo
  pod 'Fabric'
  pod 'Crashlytics'

  target 'FastlanceDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'FastlanceDemo-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FastlanceDemo-tvOS

  target 'FastlanceDemo-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
