# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :beta do
    # add actions here: https://docs.fastlane.tools/actions
    # 1
    increment_build_number
    # 2
    match(type: "development")
    # 3
    gym(
      scheme: "FastlanceDemo",
      export_method: "development",
      xcargs: "ARCHIVE=YES")
    # 4
    crashlytics(
      api_token: "687dc2e65b29ad2bcfc2f5885f806b11f63b78f0",
      build_secret: "a32fd6172b76fd213b9890dc599fee4229f317a4c75dc64169db241cfb7c233d",
      groups: "iOS",
      notes: change_log_since_last_tag
    )
  end

  lane :register_a_device do
    register_devices(
      devices: {
        "An iPhone": "45f461cac04c67d61ad9f800fc2edf64c1bad2e7",
      })
    refresh_profiles
  end

  # A helper lane for refreshing provisioning profiles.
  lane :refresh_profiles do
    match(
      type: "development",
      force: true)
    match(
      type: "adhoc",
      force: true)
  end

  def change_log_since_last_tag
    # 5
    return changelog_from_git_commits(pretty: '%h %s')
  end
end
