# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  lane :beta_android do
    increment_build_number
    gradle(task: "assembleRelease")
    crashlytics(
      api_token: "687dc2e65b29ad2bcfc2f5885f806b11f63b78f0",
      build_secret: "a32fd6172b76fd213b9890dc599fee4229f317a4c75dc64169db241cfb7c233d",
      groups: "android",
      notes: change_log_since_last_tag
    )
  end
  
  def change_log_since_last_tag
    return changelog_from_git_commits(pretty: '%h %s')
  end
end
